id = "profidev/hypr-screen-mirror"
name = "Hypr-Screen-Mirror"
version = "0.1.0"
plugin_api = 5
author = "profidev"
license = "MIT"
dependencies = ["hyprctl", "socat"]
tags = ["utility", "hyprland"]
icon = "screen-share"
description = "A plugin to quickly enable and disable screen mirroring in Hyprland."

[[widget]]
id = "widget"
entry = "widget.luau"

  [[widget.setting]]
  key = "glyph"
  type = "glyph"
  label_key = "widget.glyph.label"
  description_key = "widget.glyph.description"
  default = "screen-share"

[[panel]]
id = "panel"
entry = "panel.luau"
width = 300
height = 265
placement = "floating"
position = "center"

[[service]]
id = "service"
entry = "service.luau"
